name: Continuous Integration
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Continuous Integration Build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Build and Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B -Drevision=$GITHUB_RUN_NUMBER verify
      - name: Extract Version
        run: |
          echo "IMAGE_NAME=ghcr.io/$GITHUB_REPOSITORY:$(mvn help:evaluate -Drevision=$GITHUB_RUN_NUMBER -Dexpression=version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Build Image
        run: mvn -DskipTests -Drevision=$GITHUB_RUN_NUMBER -Dspring-boot.build-image.imageName=$IMAGE_NAME spring-boot:build-image
      - name: Push Image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          docker push $IMAGE_NAME
          docker logout